# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Frontend CI

on:
  push:
    branches: [ "master" ]
    paths:
      - 'marketplace-frontend/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'marketplace-frontend/**'

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: marketplace-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build
        run: npm run build

